### ISSUE TITLE
无法适配pot3.0.5

### ISSUE THREAD

**Issue by suibianzai** [TechDecryptor/pot-app-translate-plugin-papago#2]
首先感谢开发插件！
papago这个无法适配pot3.0.5，导入失败，不知是否考虑更新？

**Comment by zeta987** [comment]
> 首先感谢开发插件！ papago这个无法适配pot3.0.5，导入失败，不知是否考虑更新？

目前已經提交修復的 PR #3 ，已經測試成功，目前正在等待審查與合併
若有急需可以先從 PR #3 複製 `main.js` 的代碼，覆蓋原本的 `main.js` 後保存，將 `main.js`, `info.json` 以及 `icon.png` 壓縮成 `.zip` ，並將文件名稱改成 `plugin.com.TechDecryptor.papago.potext` 即可導入 POT 使用

測試成功截圖：
![測試成功](https://github.com/user-attachments/assets/e1a27b95-d32d-44e6-9b52-b63d204cc84d)

**Comment by suibianzai** [comment]
> > 首先感谢开发插件！ papago这个无法适配pot3.0.5，导入失败，不知是否考虑更新？
> 
> 目前已經提交修復的 PR #3 ，已經測試成功，目前正在等待審查與合併 若有急需可以先從 PR #3 複製 `main.js` 的代碼，覆蓋原本的 `main.js` 後保存，將 `main.js`, `info.json` 以及 `icon.png` 壓縮成 `.zip` ，並將文件名稱改成 `plugin.com.TechDecryptor.papago.potext` 即可導入 POT 使用
> 
> 測試成功截圖： ![測試成功](https://private-user-images.githubusercontent.com/126369952/374354679-e1a27b95-d32d-44e6-9b52-b63d204cc84d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODgxNjAsIm5iZiI6MTcyODg4Nzg2MCwicGF0aCI6Ii8xMjYzNjk5NTIvMzc0MzU0Njc5LWUxYTI3Yjk1LWQzMmQtNDRlNi05YjUyLWI2M2QyMDRjYzg0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwNjM3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGFkYzU5OWU5NTJlNzIzMjI5MjJiOGQ2MjBmZDBjMTU5MWJlNmNlOWJhNzc1NzEzYzY1Zjk5ZmQwOGQ0YTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Eu0XwGOd0v1bIaKNJkwQwIkWBN-zY93k8ZzG-scgX8s)

感谢修复！请问应该下载x86_64-pc-windows-msvc.zip这个文件吗？请问main.js这个文件从哪里获得呢？我把[plugin].com.TechDecryptor.papago.potext后缀修改成zip之后，只得到plugin.dll、info.json、icon.png这三个文件，没有看到main.js这个文件。

**Comment by zeta987** [comment]
> > > 首先感谢开发插件！ papago这个无法适配pot3.0.5，导入失败，不知是否考虑更新？
> > 
> > 
> > 目前已經提交修復的 PR #3 ，已經測試成功，目前正在等待審查與合併 若有急需可以先從 PR #3 複製 `main.js` 的代碼，覆蓋原本的 `main.js` 後保存，將 `main.js`, `info.json` 以及 `icon.png` 壓縮成 `.zip` ，並將文件名稱改成 `plugin.com.TechDecryptor.papago.potext` 即可導入 POT 使用
> > 測試成功截圖： ![測試成功](https://private-user-images.githubusercontent.com/126369952/374354679-e1a27b95-d32d-44e6-9b52-b63d204cc84d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODgxNjAsIm5iZiI6MTcyODg4Nzg2MCwicGF0aCI6Ii8xMjYzNjk5NTIvMzc0MzU0Njc5LWUxYTI3Yjk1LWQzMmQtNDRlNi05YjUyLWI2M2QyMDRjYzg0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwNjM3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGFkYzU5OWU5NTJlNzIzMjI5MjJiOGQ2MjBmZDBjMTU5MWJlNmNlOWJhNzc1NzEzYzY1Zjk5ZmQwOGQ0YTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Eu0XwGOd0v1bIaKNJkwQwIkWBN-zY93k8ZzG-scgX8s)
> 
> 感谢修复！请问应该下载x86_64-pc-windows-msvc.zip这个文件吗？请问main.js这个文件从哪里获得呢？我把[plugin].com.TechDecryptor.papago.potext后缀修改成zip之后，只得到plugin.dll、info.json、icon.png这三个文件，没有看到main.js这个文件。

今天已經合併成功，可以直接到 [Releases](https://github.com/TechDecryptor/pot-app-translate-plugin-papago/releases/tag/2.0.0) 下載 `plugin.com.TechDecryptor.papago.potext` 導入POT 即可

**Comment by suibianzai** [comment]
> > > > 首先感谢开发插件！ papago这个无法适配pot3.0.5，导入失败，不知是否考虑更新？
> > > 
> > > 
> > > 目前已經提交修復的 PR #3 ，已經測試成功，目前正在等待審查與合併 若有急需可以先從 PR #3 複製 `main.js` 的代碼，覆蓋原本的 `main.js` 後保存，將 `main.js`, `info.json` 以及 `icon.png` 壓縮成 `.zip` ，並將文件名稱改成 `plugin.com.TechDecryptor.papago.potext` 即可導入 POT 使用
> > > 測試成功截圖： ![測試成功](https://private-user-images.githubusercontent.com/126369952/374354679-e1a27b95-d32d-44e6-9b52-b63d204cc84d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODgxNjAsIm5iZiI6MTcyODg4Nzg2MCwicGF0aCI6Ii8xMjYzNjk5NTIvMzc0MzU0Njc5LWUxYTI3Yjk1LWQzMmQtNDRlNi05YjUyLWI2M2QyMDRjYzg0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwNjM3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGFkYzU5OWU5NTJlNzIzMjI5MjJiOGQ2MjBmZDBjMTU5MWJlNmNlOWJhNzc1NzEzYzY1Zjk5ZmQwOGQ0YTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Eu0XwGOd0v1bIaKNJkwQwIkWBN-zY93k8ZzG-scgX8s)
> > 
> > 
> > 感谢修复！请问应该下载x86_64-pc-windows-msvc.zip这个文件吗？请问main.js这个文件从哪里获得呢？我把[plugin].com.TechDecryptor.papago.potext后缀修改成zip之后，只得到plugin.dll、info.json、icon.png这三个文件，没有看到main.js这个文件。
> 
> 今天已經合併成功，可以直接到 [Releases](https://github.com/TechDecryptor/pot-app-translate-plugin-papago/releases/tag/2.0.0) 下載 `plugin.com.TechDecryptor.papago.potext` 導入POT 即可

已经能正常使用了 感谢您的更新🙏🏻🙏🏻
